name: Verify types

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MONGO_URI:
        required: true
  pull_request:
    branches:
      - main
    paths:
      - types/**/*.ts
  push:
    branches:
      - main
    paths:
      - types/**/*.ts
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Verify types
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y python3-pip
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install 18
          nvm use 18
          npm install
      - name: Verify types
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          npm run test
